import os

SPRING_BOOT_BASE_URL = os.getenv("SPRING_BOOT_BASE_URL", "http://127.0.0.1:8080")
SPRING_BOOT_TIMEOUT_SECONDS = float(os.getenv("SPRING_BOOT_TIMEOUT_SECONDS", "5"))

ATTACHMENT_DOWNLOAD_TIMEOUT_SECONDS = float(
    os.getenv("ATTACHMENT_DOWNLOAD_TIMEOUT_SECONDS", "15")
)
ATTACHMENT_MAX_SIZE_BYTES = int(os.getenv("ATTACHMENT_MAX_SIZE_BYTES", str(20 * 1024 * 1024)))
ZIP_MAX_ENTRY_COUNT = int(os.getenv("ZIP_MAX_ENTRY_COUNT", "20"))
ZIP_MAX_UNCOMPRESSED_SIZE_BYTES = int(
    os.getenv("ZIP_MAX_UNCOMPRESSED_SIZE_BYTES", str(100 * 1024 * 1024))
)
